export const COMPANY_SIGNIN_REQUEST = 'COMPANY_SIGNIN_REQUEST'
export const COMPANY_SIGNIN_SUCESS = 'COMPANY_SIGNIN_SUCESS'
export const COMPANY_SIGNIN_FAIL = 'COMPANY_SIGNIN_FAIL'
export const COMPANY_SIGNIN_RESET = 'COMPANY_SIGNIN_RESET'